# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

# Site settings
title: Deep Dungeon Compendium
email: your-email@example.com
description: >-
  A compilation of information regarding the Palace of the Dead and Heaven on
  High deep dungeons in Final Fantasy XIV. Intended for use as a guide to both
  groups and solo players looking to clear on any job.
baseurl: "" # the subpath of your site, e.g. /blog
url: ""     # the base hostname & protocol for your site, e.g. http://example.com
github_username: djcooke
ga_measurement_id: G-9Y46PNPE95

# Collections directory
collections_dir: collections

collections:
  potd_floorsets:
    output: true
    max_floor: 200
  hoh_floorsets:
    output: true
    max_floor: 100
  eo_floorsets:
    output: true
    max_floor: 100

  potd_001_enemies:
    output: false
  potd_011_enemies:
    output: false
  potd_021_enemies:
    output: false
  potd_031_enemies:
    output: false
  potd_041_enemies:
    output: false
  potd_051_enemies:
    output: false
  potd_061_enemies:
    output: false
  potd_071_enemies:
    output: false
  potd_081_enemies:
    output: false
  potd_091_enemies:
    output: false
  potd_101_enemies:
    output: false
  potd_111_enemies:
    output: false
  potd_121_enemies:
    output: false
  potd_131_enemies:
    output: false
  potd_141_enemies:
    output: false
  potd_151_enemies:
    output: false
  potd_161_enemies:
    output: false
  potd_171_enemies:
    output: false
  potd_181_enemies:
    output: false
  potd_191_enemies:
    output: false

  hoh_001_enemies:
    output: false
  hoh_011_enemies:
    output: false
  hoh_021_enemies:
    output: false
  hoh_031_enemies:
    output: false
  hoh_041_enemies:
    output: false
  hoh_051_enemies:
    output: false
  hoh_061_enemies:
    output: false
  hoh_071_enemies:
    output: false
  hoh_081_enemies:
    output: false
  hoh_091_enemies:
    output: false

  eo_001_enemies:
    output: false
  eo_011_enemies:
    output: false
  eo_021_enemies:
    output: false
  eo_031_enemies:
    output: false
  eo_041_enemies:
    output: false
  eo_051_enemies:
    output: false
  eo_061_enemies:
    output: false
  eo_071_enemies:
    output: false
  eo_081_enemies:
    output: false
  eo_091_enemies:
    output: false

defaults:
  - scope:
      path: ""
      type: "potd_floorsets"
    values:
      layout: "floorset"
  - scope:
      path: ""
      type: "hoh_floorsets"
    values:
      layout: "floorset"
  - scope:
      path: ""
      type: "eo_floorsets"
    values:
      layout: "floorset"
  - scope:
      path: "pages"
      type: "pages"
    values:
      layout: "default"
      permalink: "/:basename/"

include:
  - pages

exclude:
  - templates

# Build settings
theme: null
# plugins:
#   - jekyll-feed
